"use client";

import { FormEvent } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight, MessageCircle } from "lucide-react";

export default function Contact(){
  const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const message=`Hi Buildly! I'd like to discuss a project.\n\nName: ${data.get("name")}\nBusiness: ${data.get("business")}\nEmail: ${data.get("email")}\nPhone: ${data.get("phone")}\nService: ${data.get("service")}\nBudget: ${data.get("budget")}\n\nProject details:\n${data.get("details")}`;window.open(`https://wa.me/923202729210?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer");};
  return <section className="section" id="contact"><div className="shell"><motion.div className="contact-shell" initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.8}}><div className="contact-orb" aria-hidden="true"/><div className="contact-head"><span className="eyebrow">Start a project</span><h2>Let’s build what’s <span className="gradient-text">next.</span></h2><p>Share a few details and your message will open in WhatsApp, ready to send. We usually reply within one business day.</p></div><form className="contact-form" onSubmit={submit}><Field label="Full name" name="name" placeholder="Your name" required/><Field label="Business" name="business" placeholder="Company or brand"/><Field label="Email" name="email" type="email" placeholder="you@company.com" required/><Field label="Phone" name="phone" type="tel" placeholder="+92 ..."/><div className="field"><label htmlFor="service">Required service</label><select id="service" name="service" defaultValue="Website Development" required><option>Website Development</option><option>SaaS Development</option><option>AI Applications</option><option>AI Automation</option><option>Business Automation</option><option>Mobile App</option><option>Desktop Application</option><option>API Development</option><option>UI and UX Design</option><option>E Commerce</option><option>Landing Page</option><option>MVP Development</option><option>Custom Software</option></select></div><div className="field"><label htmlFor="budget">Budget</label><select id="budget" name="budget" defaultValue="Let's discuss"><option>Let&apos;s discuss</option><option>$1k – $3k</option><option>$3k – $8k</option><option>$8k – $15k</option><option>$15k+</option></select></div><div className="field full"><label htmlFor="details">Project details</label><textarea id="details" name="details" placeholder="Tell us about the product, problem, timeline, and what a great outcome looks like." required/></div><div className="submit-row"><p>No spam. No sales scripts. Just a useful first conversation.</p><button className="pill-button pill-primary" type="submit"><MessageCircle size={16}/> Send via WhatsApp <ArrowUpRight size={15}/></button></div></form></motion.div></div></section>;
}

function Field({label,name,type="text",placeholder,required=false}:{label:string;name:string;type?:string;placeholder:string;required?:boolean}){return <div className="field"><label htmlFor={name}>{label}</label><input id={name} name={name} type={type} placeholder={placeholder} required={required}/></div>}
